import Head from 'next/head'
import Header from '../components/Header'


export default function Home() {
  return (
    <div className='container w-4/5 mx-auto bg-slate-700' dir='rtl'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2 className='text-red-700 text-2xl'>aaaaaaaaa</h2>
      <Header />
    </div>
  )
}
