import Head from 'next/head'
import Header from '../components/Header'




import Link from 'next/link'
export default function Home() {
  return (
    <div className='bg-gray-400'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header />
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi voluptatum neque ad quo consequatur porro deserunt, quod, illo id eos cupiditate, ex quis dolore laborum asperiores nobis enim. Sed, dolore.
        Esse nostrum 12222 repellendus, molestias minima eveniet reiciendis magni vitae qui nihil, totam fuga deserunt facilis delectus odit. Deserunt quidem aspernatur dolores quae ea placeat ab? Veritatis reprehenderit nisi sapiente sit?</p>
    </div>
  )
}
